"""Updated Insights Attribute

Revision ID: 0e59c4866fae
Revises: 926044e8ec53
Create Date: 2026-07-25 17:16:41.425645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e59c4866fae'
down_revision: Union[str, Sequence[str], None] = '926044e8ec53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        'resumes',
        'insight',
        existing_type=sa.VARCHAR(length=4000),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        postgresql_using="insight::jsonb",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'insight',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=4000),
               existing_nullable=True)
    # ### end Alembic commands ###
