"""initial tables

Revision ID: 3600fa92b896
Revises: a55a390ce8d9
Create Date: 2026-06-13 18:32:32.396152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3600fa92b896'
down_revision: Union[str, Sequence[str], None] = 'a55a390ce8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('templates', sa.Column('layout', sa.String(length=10), nullable=False))
#     op.add_column('templates', sa.Column('preview_bg', sa.String(length=20), nullable=False))
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_column('templates', 'preview_bg')
#     op.drop_column('templates', 'layout')
#     # ### end Alembic commands ###


# def upgrade() -> None:
#     op.add_column("templates", sa.Column("layout",     sa.String(10),  nullable=True))
#     op.add_column("templates", sa.Column("preview_bg", sa.String(20),  nullable=True))

# def downgrade() -> None:
#     op.drop_column("templates", "preview_bg")
#     op.drop_column("templates", "layout")


def upgrade() -> None:
    # Add columns as nullable first
    op.add_column('templates', sa.Column('layout',     sa.String(10), nullable=True))
    op.add_column('templates', sa.Column('preview_bg', sa.String(20), nullable=True))

    # Backfill existing rows
    op.execute("UPDATE templates SET layout = 'A'        WHERE layout IS NULL")
    op.execute("UPDATE templates SET preview_bg = '#ffffff' WHERE preview_bg IS NULL")

    # Now tighten to NOT NULL
    op.alter_column('templates', 'layout',     nullable=False)
    op.alter_column('templates', 'preview_bg', nullable=False)


def downgrade() -> None:
    op.drop_column('templates', 'preview_bg')
    op.drop_column('templates', 'layout')