"""Added Image Table to user model

Revision ID: c2de3144a070
Revises: 7fc0560393bc
Create Date: 2026-07-12 09:24:51.666026

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c2de3144a070"
down_revision: Union[str, Sequence[str], None] = "7fc0560393bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("image", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "image")
    # ### end Alembic commands ###
