"""Update Template table and its data

Revision ID: d0db810fe08b
Revises: 3600fa92b896
Create Date: 2026-06-30 19:26:40.441088

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d0db810fe08b"
down_revision: Union[str, Sequence[str], None] = "3600fa92b896"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('templates', sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###\
    op.add_column(
        "templates",
        sa.Column(
            "sections",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.alter_column("templates", "sections", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("templates", "sections")
    # ### end Alembic commands ###
